#!/usr/bin/env python

import sys
from RPLCD.gpio import CharLCD
from RPi import GPIO

if len(sys.argv) < 2:
    print("\033[31m No text given, please provide a text.\n \033[mUsage write_to_text <text>")
else:
    lcd = CharLCD(cols=16, rows=2,
        dotsize=8, charmap='A02',
        auto_linebreaks=True,
        pin_rs=37, pin_e=35,
        pins_data=[33, 31, 29, 23],
        numbering_mode=GPIO.BOARD)

    lcd.write_string(sys.argv[1])
